name: Deploy to Amazon Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.13'  # Specify the Python version you need
  
        
      # Set up AWS SAM CLI
      - uses: aws-actions/setup-sam@v2

      # Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Build the Lambda function
      - run: sam build --use-container

      # Deploy the Lambda function
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides "GeminiApiKey=${{ secrets.GEMINI_API_SECRET_KEY }}"

